# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxWebView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod ’RxCocoa’,    ’~> 4.3.1’
pod ’RxSwift’,    ’~> 4.3.1’
pod ’RxOptional’, ’~> 3.5.0’
  # Pods for RxWebView

end
